version: '3.5'

services:
  clickhouse:
    image: yandex/clickhouse-server:20.7
    container_name: clickhouse
    hostname: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
  vertica:
    image: jbfavre/vertica:latest
    container_name: vertica
    hostname: vertica
    restart: always
    ports:
      - "5433:5433"
    environment:
      APP_DB_USER: "dbadmin"
      APP_DB_PASSWORD: "dbpass"
      APP_DB_NAME: "docker"
  jupyter:
    image: python:slim
    container_name: jupyter
    command: bash -c "pip install jupyter clickhouse-driver vertica-python mimesis && jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root"
    ports:
      - "8888:8888"
    volumes:
      - ./volume:/home/user
